name: PR
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33

      - name: Build
        run: go build
